############# French navigation ##############
# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "How It Works"
url = "how-it-works/"
weight = 2

[[main]]
name = "Pricing"
url = "pricing-2/"
weight = 3

# Footer menus
[[footerproduct]]
name = "How It Works"
url = "how-it-works/"
weight = 1
  
[[footerproduct]]
name = "Pricing"
url = "pricing-2/"
weight = 2

[[footerproduct]]
name = "Roadmap"
url = "https://trello.com/b/WIyV4Y36/platypeeps-public-roadmap"
weight = 3

[[footersupport]]
name = "Docs"
url = "https://doc.platypeeps.com/"
weight = 1

[[footersupport]]
name = "Faq"
url = "faq/"
weight = 2

[[footersupport]]
name = "Status"
url = "https://rootly.io/teams/platypeeps/status-pages/platypeeps-8cbc6ebb-db1e-4fbf-a98e-cc16a0c5a3aa/public"
weight = 3

[[footersupport]]
name = "Contact"
url = "contact/"
weight = 3

[[footercompany]]
name = "About"
url = "about/"
weight = 1

[[footercompany]]
name = "Blog"
url = "blog/"
weight = 2

[[footercompany]]
name = "Team"
url = "team/"
weight = 4

[[footercompany]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 5

[[footercompany]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 6

